ANDROID: debug_kinfo: fix build issue due to module_alloc_base change
In commit 3e35d303ab7d ("arm64: module: rework module VA range
selection"), the module_alloc_base variable is changed to
static module_direct_base and module_plt_base.

Remove those fiedls from debug_kinfo structure to fix build error.
common/drivers/android/debug_kinfo.c:165:26: error: use of undeclared identifier 'module_alloc_base'
        info->module_start_va = module_alloc_base;
                                ^

Bug: 317938461
Change-Id: I817d5a30ed3e6be3b1e4998541d4a46a4bbd7dd4
Signed-off-by: Kuan-Ying Lee <Kuan-Ying.Lee@mediatek.com>