usb: host: ohci-spear: fix ohci_dump parameters
Commit 6a04d05acfb51355 ("USB: OHCI: fix bugs in debug routines") has removed
the unused `verbose' argument of the debug function ohci_dump(); adapt
ohci-spear accordingly.

This fixes the following compilation error:

  drivers/usb/host/ohci-spear.c: In function ‘ohci_spear_start’:
  drivers/usb/host/ohci-spear.c:56:2: error: too many arguments to function ‘ohci_dump’

Signed-off-by: Vincent Stehlé <vincent.stehle@laposte.net>
Acked-by: Alan Stern <stern@rowland.harvard.edu>
Cc: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Signed-off-by: Jiri Slaby <jslaby@suse.cz>