fixup! ASoC: Add support for all the downstream rpi sound card drivers
* Change SND_PIMIDI and SND_PISOUND_MICRO to select CRC8 instead of depend
  on it.
* Fixes build with Clang.

sound/drivers/upisnd/upisnd_codec.c:741:6: error: variable 'ret' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
  741 |         if (adau->clk_src != ADAU1961_CLK_SRC_MCLK)
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
sound/drivers/upisnd/upisnd_codec.c:744:9: note: uninitialized use occurs here
  744 |         return ret;
      |                ^~~
sound/drivers/upisnd/upisnd_codec.c:741:2: note: remove the 'if' if its condition is always true
  741 |         if (adau->clk_src != ADAU1961_CLK_SRC_MCLK)
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  742 |                 ret = snd_soc_dapm_add_routes(dapm, &adau1961_dapm_pll_route, 1);
sound/drivers/upisnd/upisnd_codec.c:739:9: note: initialize the variable 'ret' to silence this warning
  739 |         int ret;
      |                ^
      |                 = 0
1 error generated.