Fix Intel XE driver non compiling
When trying to compile with CONFIG_DRM_XE enabled, the build fails with the following error

```
/build/drivers/gpu/drm/i915/display/intel_display.c: In function 'intel_atomic_commit':
/build/drivers/gpu/drm/i915/display/intel_display.c:7830:80: error: macro 'for_each_new_intel_crtc_in_state' passed 4 arguments, but takes just 3
 7830 |                 for_each_new_intel_crtc_in_state(state, crtc, new_crtc_state, i)
      |                                                                                ^
In file included from /build/drivers/gpu/drm/i915/display/intel_display_types.h:49,
                 from /build/drivers/gpu/drm/i915/display/intel_display.c:78:
/build/drivers/gpu/drm/i915/display/intel_display.h:294:9: note: macro 'for_each_new_intel_crtc_in_state' defined here
  294 | #define for_each_new_intel_crtc_in_state(__state, crtc, new_crtc_state) \
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/build/drivers/gpu/drm/i915/display/intel_display.c:7830:17: error: unknown type name 'for_each_new_intel_crtc_in_state'
 7830 |                 for_each_new_intel_crtc_in_state(state, crtc, new_crtc_state, i)
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/build/drivers/gpu/drm/i915/display/intel_display.c:7831:38: error: expected declaration specifiers or '...' before '&' token
 7831 |                         complete_all(&new_crtc_state->uapi.commit->flip_done);
      |                                      ^
/build/drivers/gpu/drm/i915/display/intel_display.c:7828:21: warning: unused variable 'i' [-Wunused-variable]
 7828 |                 int i;
      |                     ^
/build/drivers/gpu/drm/i915/display/intel_display.c:7827:36: warning: unused variable 'crtc' [-Wunused-variable]
 7827 |                 struct intel_crtc *crtc;
      |                                    ^~~~
/build/drivers/gpu/drm/i915/display/intel_display.c:7826:42: warning: unused variable 'new_crtc_state' [-Wunused-variable]
 7826 |                 struct intel_crtc_state *new_crtc_state;
```

This is because upstream commit a6166f52433e49 left an iterator after the upstream macro changed from 4 to 3 arguments.