gpio: pwm: Fix return type of pwm_gpio_set
Fixes the following build failure:

drivers/gpio/gpio-pwm.c:108:26: error: assignment to 'int (*)(struct gpio_chip *, unsigned int,  int)' from incompatible pointer type 'void (*)(struct gpio_chip *, unsigned int,  int)' [-Wincompatible-pointer-types]
  108 |         pwm_gpio->gc.set = pwm_gpio_set;
      |                          ^
drivers/gpio/gpio-pwm.c:30:13: note: 'pwm_gpio_set' declared here
   30 | static void pwm_gpio_set(struct gpio_chip *gc, unsigned int off, int val)
      |             ^~~~~~~~~~~~

Fixes: 8b95d76cd44e ("drivers/gpio: Add a driver that wraps the PWM API as a GPIO controller")
Signed-off-by: Juerg Haefliger <juerg.haefliger@canonical.com>